"""Evidence verification: every quote the model returns must be found in a stored transcript segment.
Timestamps are derived from the stored segment/words, never generated by the model."""

from __future__ import annotations

import difflib
import re
from dataclasses import dataclass, field
from typing import Any

_WORD = re.compile(r"[\w%]+(?:[-'][\w]+)*", re.UNICODE)


@dataclass
class SegmentView:
    id: str
    alias: str
    text: str
    start_ms: int
    end_ms: int
    revision_id: str
    speaker_label: str | None = None
    speaker_name: str | None = None
    speaker_participant_id: str | None = None
    words: list[dict[str, Any]] = field(default_factory=list)
    order: int = 0


@dataclass
class EvidenceRef:
    segment_id: str
    alias: str
    revision_id: str
    quote: str
    match: str  # exact | fuzzy | missing
    char_start: int | None = None
    char_end: int | None = None
    start_ms: int | None = None
    end_ms: int | None = None
    note: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return dict(self.__dict__)


def _norm_tokens(text: str) -> list[tuple[str, int, int]]:
    return [(m.group(0).lower().replace("ё", "е"), m.start(), m.end()) for m in _WORD.finditer(text)]


def _timing(seg: SegmentView, char_start: int, char_end: int) -> tuple[int, int]:
    if not seg.words or not seg.text:
        return seg.start_ms, seg.end_ms
    # map by relative position of characters to words (words carry absolute seconds)
    n = len(seg.words)
    first = min(n - 1, int(char_start / max(len(seg.text), 1) * n))
    last = min(n - 1, max(first, int((char_end - 1) / max(len(seg.text), 1) * n)))
    return int(seg.words[first]["s"] * 1000), int(seg.words[last]["e"] * 1000)


def locate(quote: str | None, seg: SegmentView, threshold: float = 0.84) -> EvidenceRef:
    if not quote or not quote.strip():
        return EvidenceRef(seg.id, seg.alias, seg.revision_id, quote or "", "missing", note="цитата отсутствует")
    q = _norm_tokens(quote)
    s = _norm_tokens(seg.text)
    if not q or not s:
        return EvidenceRef(seg.id, seg.alias, seg.revision_id, quote, "missing", note="пустой текст")
    qw = [t for t, _, _ in q]
    sw = [t for t, _, _ in s]
    for i in range(len(sw) - len(qw) + 1):
        if sw[i:i + len(qw)] == qw:
            cs, ce = s[i][1], s[i + len(qw) - 1][2]
            st, en = _timing(seg, cs, ce)
            return EvidenceRef(seg.id, seg.alias, seg.revision_id, seg.text[cs:ce], "exact", cs, ce, st, en)
    best = (0.0, -1, 0)
    joined_q = " ".join(qw)
    for width in {max(1, len(qw) - 1), len(qw), len(qw) + 1}:
        for i in range(0, max(1, len(sw) - width + 1)):
            cand = " ".join(sw[i:i + width])
            ratio = difflib.SequenceMatcher(None, joined_q, cand).ratio()
            if ratio > best[0]:
                best = (ratio, i, width)
    ratio, i, width = best
    if ratio >= threshold and i >= 0:
        cs, ce = s[i][1], s[min(len(s), i + width) - 1][2]
        st, en = _timing(seg, cs, ce)
        return EvidenceRef(seg.id, seg.alias, seg.revision_id, seg.text[cs:ce], "fuzzy", cs, ce, st, en,
                           note=f"неточное совпадение ({ratio:.2f})")
    return EvidenceRef(seg.id, seg.alias, seg.revision_id, quote, "missing",
                       note="цитата не найдена в тексте сегмента")


def verify(quote: str | None, alias: str, segments: dict[str, SegmentView],
           ordered: list[SegmentView]) -> EvidenceRef:
    """Locate the quote in the cited segment, then (with a note) in its immediate neighbours."""
    seg = segments.get(alias)
    if seg is None:
        return EvidenceRef("", alias, "", quote or "", "missing", note=f"сегмент {alias} не существует")
    ref = locate(quote, seg)
    if ref.match != "missing" or not quote:
        return ref
    for neighbour in (seg.order - 1, seg.order + 1):
        if 0 <= neighbour < len(ordered):
            alt = locate(quote, ordered[neighbour])
            if alt.match != "missing":
                alt.note = f"основание найдено в соседнем сегменте {ordered[neighbour].alias}, а не в {alias}"
                return alt
    return ref


NUMBER_RE = re.compile(r"\d+(?:[.,]\d+)?\s?%?")


def numbers_in(text: str) -> set[str]:
    """Numbers written with digits or Russian/Kazakh number words ('семьдесят один' -> '71')."""
    from hattama.domain.numbers import parse_kk_number, parse_ru_cardinal

    found = {m.group(0).replace(" ", "").replace(",", ".").rstrip("%") for m in NUMBER_RE.finditer(text)}
    tokens = re.findall(r"[\w]+", text.lower().replace("ё", "е"))
    i = 0
    while i < len(tokens):
        parsed = parse_ru_cardinal(tokens[i:i + 2]) if not tokens[i].isdigit() else None
        if parsed is None and not tokens[i].isdigit():
            parsed = parse_kk_number(tokens[i:i + 3])
        if parsed:
            found.add(str(parsed[0]))
            i += parsed[1]
        else:
            i += 1
    return found


def numbers_supported(text: str, evidence_text: str) -> list[str]:
    """Numbers in a summary statement that do NOT appear in its evidence (must be empty)."""
    available = numbers_in(evidence_text)
    missing = []
    for m in NUMBER_RE.finditer(text):
        digits = m.group(0).replace(" ", "").replace(",", ".").rstrip("%")
        if digits not in available:
            missing.append(m.group(0).strip())
    return missing
