"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-23 15:19:34.620099
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import hattama.db.types


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meeting_id', sa.String(length=32), nullable=True),
    sa.Column('actor_user_id', sa.String(length=32), nullable=True),
    sa.Column('actor_kind', sa.String(length=12), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('object_type', sa.String(length=30), nullable=True),
    sa.Column('object_id', sa.String(length=32), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('at', hattama.db.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_meeting_id'), ['meeting_id'], unique=False)
        batch_op.create_index('ix_audit_object', ['object_type', 'object_id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('queue', sa.String(length=20), nullable=False),
    sa.Column('meeting_id', sa.String(length=32), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=12), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('lease_owner', sa.String(length=80), nullable=True),
    sa.Column('lease_expires_at', hattama.db.types.UTCDateTime(), nullable=True),
    sa.Column('run_after', hattama.db.types.UTCDateTime(), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('progress', sa.JSON(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', hattama.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', hattama.db.types.UTCDateTime(), nullable=False),
    sa.Column('finished_at', hattama.db.types.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_claim', ['state', 'queue', 'run_after'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_meeting_id'), ['meeting_id'], unique=False)

    op.create_table('live_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meeting_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', hattama.db.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('live_events', schema=None) as batch_op:
        batch_op.create_index('ix_live_events_meeting', ['meeting_id', 'id'], unique=False)

    op.create_table('metric_samples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meeting_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.Column('at', hattama.db.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metric_samples', schema=None) as batch_op:
        batch_op.create_index('ix_metrics_meeting_name', ['meeting_id', 'name'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('meeting_id', sa.String(length=32), nullable=True),
    sa.Column('action_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('scheduled_for', hattama.db.types.UTCDateTime(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', hattama.db.types.UTCDateTime(), nullable=False),
    sa.Column('delivered_at', hattama.db.types.UTCDateTime(), nullable=True),
    sa.Column('read_at', hattama.db.types.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_action_id'), ['action_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_meeting_id'), ['meeting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_scheduled_for'), ['scheduled_for'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('resource_locks',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('owner', sa.String(length=80), nullable=True),
    sa.Column('expires_at', hattama.db.types.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', hattama.db.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('auth_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', hattama.db.types.UTCDateTime(), nullable=False),
    sa.Column('expires_at', hattama.db.types.UTCDateTime(), nullable=False),
    sa.Column('revoked_at', hattama.db.types.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('meetings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('meeting_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('language_mode', sa.String(length=10), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('meeting_url', sa.String(length=2000), nullable=True),
    sa.Column('owner_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('consent_text', sa.Text(), nullable=True),
    sa.Column('consent_confirmed_at', hattama.db.types.UTCDateTime(), nullable=True),
    sa.Column('consent_confirmed_by', sa.String(length=32), nullable=True),
    sa.Column('protocol_version', sa.Integer(), nullable=False),
    sa.Column('active_transcript_revision_id', sa.String(length=32), nullable=True),
    sa.Column('active_summary_id', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', hattama.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', hattama.db.types.UTCDateTime(), nullable=False),
    sa.Column('deleted_at', hattama.db.types.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['consent_confirmed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meetings_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meetings_status'), ['status'], unique=False)

    op.create_table('action_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('meeting_id', sa.String(length=32), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('origin', sa.String(length=10), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('expected_result', sa.Text(), nullable=True),
    sa.Column('assigner', sa.JSON(), nullable=True),
    sa.Column('assignee', sa.JSON(), nullable=True),
    sa.Column('assignee_type', sa.String(length=20), nullable=False),
    sa.Column('assignee_participant_id', sa.String(length=32), nullable=True),
    sa.Column('assignee_user_id', sa.String(length=32), nullable=True),
    sa.Column('curator', sa.JSON(), nullable=True),
    sa.Column('collaborators', sa.JSON(), nullable=False),
    sa.Column('deadline', sa.JSON(), nullable=False),
    sa.Column('deadline_confirmed', sa.Boolean(), nullable=False),
    sa.Column('condition', sa.Text(), nullable=True),
    sa.Column('conditional', sa.Boolean(), nullable=False),
    sa.Column('dependencies', sa.JSON(), nullable=False),
    sa.Column('parent_id', sa.String(length=32), nullable=True),
    sa.Column('topic', sa.String(length=300), nullable=True),
    sa.Column('review_state', sa.String(length=15), nullable=False),
    sa.Column('execution_state', sa.String(length=15), nullable=False),
    sa.Column('on_hold', sa.Boolean(), nullable=False),
    sa.Column('review_reasons', sa.JSON(), nullable=False),
    sa.Column('extraction_run_id', sa.String(length=32), nullable=True),
    sa.Column('local_ref', sa.String(length=16), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', hattama.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', hattama.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'fingerprint')
    )
    with op.batch_alter_table('action_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_items_assignee_participant_id'), ['assignee_participant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_items_assignee_user_id'), ['assignee_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_items_meeting_id'), ['meeting_id'], unique=False)

    op.create_table('audio_assets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('meeting_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('rel_path', sa.String(length=500), nullable=False),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('channels', sa.Integer(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('source_key', sa.String(length=32), nullable=True),
    sa.Column('capture_session_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', hattama.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audio_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audio_assets_meeting_id'), ['meeting_id'], unique=False)

    op.create_table('capture_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('meeting_id', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', hattama.db.types.UTCDateTime(), nullable=False),
    sa.Column('started_at', hattama.db.types.UTCDateTime(), nullable=True),
    sa.Column('stop_requested_at', hattama.db.types.UTCDateTime(), nullable=True),
    sa.Column('stopped_at', hattama.db.types.UTCDateTime(), nullable=True),
    sa.Column('stop_reason', sa.String(length=64), nullable=True),
    sa.Column('timeline_origin_us', sa.BigInteger(), nullable=True),
    sa.Column('client_info', sa.JSON(), nullable=False),
    sa.Column('last_frame_at', hattama.db.types.UTCDateTime(), nullable=True),
    sa.Column('connected', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('capture_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_capture_sessions_meeting_id'), ['meeting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_capture_sessions_state'), ['state'], unique=False)

    op.create_table('export_artifacts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('meeting_id', sa.String(length=32), nullable=False),
    sa.Column('protocol_version', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(length=5), nullable=False),
    sa.Column('is_draft', sa.Boolean(), nullable=False),
    sa.Column('approval_id', sa.String(length=32), nullable=True),
    sa.Column('rel_path', sa.String(length=500), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', hattama.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('export_artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_export_artifacts_meeting_id'), ['meeting_id'], unique=False)

    op.create_table('extraction_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('meeting_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('transcript_revision_id', sa.String(length=32), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('windows_total', sa.Integer(), nullable=False),
    sa.Column('windows_done', sa.Integer(), nullable=False),
    sa.Column('last_segment_seq', sa.Integer(), nullable=False),
    sa.Column('state', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('started_at', hattama.db.types.UTCDateTime(), nullable=False),
    sa.Column('finished_at', hattama.db.types.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'idempotency_key')
    )
    with op.batch_alter_table('extraction_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extraction_runs_meeting_id'), ['meeting_id'], unique=False)

    op.create_table('meeting_members',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('meeting_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'user_id')
    )
    with op.batch_alter_table('meeting_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meeting_members_meeting_id'), ['meeting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meeting_members_user_id'), ['user_id'], unique=False)

    op.create_table('participants',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('meeting_id', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('position', sa.String(length=200), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('is_present', sa.Boolean(), nullable=False),
    sa.Column('is_self', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('notified_at', hattama.db.types.UTCDateTime(), nullable=True),
    sa.Column('created_at', hattama.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participants_meeting_id'), ['meeting_id'], unique=False)

    op.create_table('protocol_approvals',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('meeting_id', sa.String(length=32), nullable=False),
    sa.Column('protocol_version', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('snapshot_sha256', sa.String(length=64), nullable=False),
    sa.Column('approved_by', sa.String(length=32), nullable=False),
    sa.Column('approved_at', hattama.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'protocol_version')
    )
    with op.batch_alter_table('protocol_approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_protocol_approvals_meeting_id'), ['meeting_id'], unique=False)

    op.create_table('review_issues',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('meeting_id', sa.String(length=32), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('object_type', sa.String(length=20), nullable=True),
    sa.Column('object_id', sa.String(length=32), nullable=True),
    sa.Column('field', sa.String(length=30), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.String(length=32), nullable=True),
    sa.Column('resolved_at', hattama.db.types.UTCDateTime(), nullable=True),
    sa.Column('created_at', hattama.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'dedupe_key')
    )
    with op.batch_alter_table('review_issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_issues_meeting_id'), ['meeting_id'], unique=False)

    op.create_table('speakers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('meeting_id', sa.String(length=32), nullable=False),
    sa.Column('revision_id', sa.String(length=32), nullable=True),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('source_key', sa.String(length=32), nullable=True),
    sa.Column('merged_into_id', sa.String(length=32), nullable=True),
    sa.Column('sample_segment_id', sa.String(length=32), nullable=True),
    sa.Column('total_speech_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', hattama.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('speakers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_speakers_meeting_id'), ['meeting_id'], unique=False)

    op.create_table('summary_revisions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('meeting_id', sa.String(length=32), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('origin', sa.String(length=10), nullable=False),
    sa.Column('transcript_revision_id', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('created_at', hattama.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'number')
    )
    with op.batch_alter_table('summary_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_summary_revisions_meeting_id'), ['meeting_id'], unique=False)

    op.create_table('transcript_revisions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('meeting_id', sa.String(length=32), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('base_revision_id', sa.String(length=32), nullable=True),
    sa.Column('asr_model', sa.String(length=100), nullable=True),
    sa.Column('asr_params', sa.JSON(), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('created_at', hattama.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'number')
    )
    with op.batch_alter_table('transcript_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transcript_revisions_meeting_id'), ['meeting_id'], unique=False)

    op.create_table('action_revisions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('action_id', sa.String(length=32), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('change_kind', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('event', sa.JSON(), nullable=True),
    sa.Column('author_user_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', hattama.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['action_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action_id', 'number')
    )
    with op.batch_alter_table('action_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_revisions_action_id'), ['action_id'], unique=False)

    op.create_table('bot_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('meeting_id', sa.String(length=32), nullable=False),
    sa.Column('capture_session_id', sa.String(length=32), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('meeting_url', sa.String(length=2000), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('state_reason', sa.Text(), nullable=True),
    sa.Column('agent_id', sa.String(length=80), nullable=True),
    sa.Column('recording_approved_by', sa.String(length=32), nullable=True),
    sa.Column('recording_approved_at', hattama.db.types.UTCDateTime(), nullable=True),
    sa.Column('admitted_at', hattama.db.types.UTCDateTime(), nullable=True),
    sa.Column('stop_requested', sa.Boolean(), nullable=False),
    sa.Column('diagnostics', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', hattama.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', hattama.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['capture_session_id'], ['capture_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bot_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bot_sessions_meeting_id'), ['meeting_id'], unique=False)

    op.create_table('capture_sources',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('capture_session_id', sa.String(length=32), nullable=False),
    sa.Column('source_key', sa.String(length=32), nullable=False),
    sa.Column('source_index', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('last_state', sa.String(length=32), nullable=True),
    sa.Column('muted', sa.Boolean(), nullable=False),
    sa.Column('created_at', hattama.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['capture_session_id'], ['capture_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('capture_session_id', 'source_index'),
    sa.UniqueConstraint('capture_session_id', 'source_key')
    )
    with op.batch_alter_table('capture_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_capture_sources_capture_session_id'), ['capture_session_id'], unique=False)

    op.create_table('evidence_spans',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('meeting_id', sa.String(length=32), nullable=False),
    sa.Column('action_id', sa.String(length=32), nullable=True),
    sa.Column('summary_id', sa.String(length=32), nullable=True),
    sa.Column('summary_item_key', sa.String(length=64), nullable=True),
    sa.Column('field', sa.String(length=20), nullable=False),
    sa.Column('segment_id', sa.String(length=32), nullable=False),
    sa.Column('transcript_revision_id', sa.String(length=32), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('start_ms', sa.BigInteger(), nullable=True),
    sa.Column('end_ms', sa.BigInteger(), nullable=True),
    sa.Column('match', sa.String(length=10), nullable=False),
    sa.Column('superseded', sa.Boolean(), nullable=False),
    sa.Column('created_at', hattama.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['action_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_spans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_spans_action_id'), ['action_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_spans_meeting_id'), ['meeting_id'], unique=False)

    op.create_table('ingest_tokens',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('capture_session_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('client_name', sa.String(length=64), nullable=False),
    sa.Column('created_at', hattama.db.types.UTCDateTime(), nullable=False),
    sa.Column('expires_at', hattama.db.types.UTCDateTime(), nullable=False),
    sa.Column('revoked_at', hattama.db.types.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['capture_session_id'], ['capture_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('ingest_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingest_tokens_capture_session_id'), ['capture_session_id'], unique=False)

    op.create_table('pairing_codes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('capture_session_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', hattama.db.types.UTCDateTime(), nullable=False),
    sa.Column('expires_at', hattama.db.types.UTCDateTime(), nullable=False),
    sa.Column('used_at', hattama.db.types.UTCDateTime(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['capture_session_id'], ['capture_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_hash')
    )
    op.create_table('speaker_bindings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('speaker_id', sa.String(length=32), nullable=False),
    sa.Column('participant_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('evidence_segment_id', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('created_at', hattama.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['speaker_id'], ['speakers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('speaker_bindings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_speaker_bindings_speaker_id'), ['speaker_id'], unique=False)

    op.create_table('transcript_segments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('meeting_id', sa.String(length=32), nullable=False),
    sa.Column('revision_id', sa.String(length=32), nullable=False),
    sa.Column('capture_session_id', sa.String(length=32), nullable=True),
    sa.Column('source_key', sa.String(length=32), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('start_ms', sa.BigInteger(), nullable=False),
    sa.Column('end_ms', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('words', sa.JSON(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('speaker_id', sa.String(length=32), nullable=True),
    sa.Column('state', sa.String(length=10), nullable=False),
    sa.Column('rev', sa.Integer(), nullable=False),
    sa.Column('overlap', sa.Boolean(), nullable=False),
    sa.Column('review_reasons', sa.JSON(), nullable=False),
    sa.Column('avg_logprob', sa.Float(), nullable=True),
    sa.Column('edited_by', sa.String(length=32), nullable=True),
    sa.Column('edited_at', hattama.db.types.UTCDateTime(), nullable=True),
    sa.Column('created_at', hattama.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revision_id'], ['transcript_revisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transcript_segments', schema=None) as batch_op:
        batch_op.create_index('ix_segments_rev_order', ['revision_id', 'start_ms'], unique=False)
        batch_op.create_index(batch_op.f('ix_transcript_segments_meeting_id'), ['meeting_id'], unique=False)

    op.create_table('source_epochs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=False),
    sa.Column('epoch', sa.Integer(), nullable=False),
    sa.Column('sample_rate', sa.Integer(), nullable=False),
    sa.Column('channel_count', sa.Integer(), nullable=False),
    sa.Column('epoch_start_wall_us', sa.BigInteger(), nullable=False),
    sa.Column('rel_path', sa.String(length=500), nullable=False),
    sa.Column('durable_sequence', sa.BigInteger(), nullable=False),
    sa.Column('durable_samples', sa.BigInteger(), nullable=False),
    sa.Column('received_frames', sa.BigInteger(), nullable=False),
    sa.Column('duplicate_frames', sa.BigInteger(), nullable=False),
    sa.Column('live_processed_samples', sa.BigInteger(), nullable=False),
    sa.Column('live_done', sa.Boolean(), nullable=False),
    sa.Column('final_sequence', sa.BigInteger(), nullable=True),
    sa.Column('closed_at', hattama.db.types.UTCDateTime(), nullable=True),
    sa.Column('close_reason', sa.String(length=32), nullable=True),
    sa.Column('created_at', hattama.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', hattama.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['capture_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'epoch')
    )
    with op.batch_alter_table('source_epochs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_epochs_source_id'), ['source_id'], unique=False)

    op.create_table('audio_gaps',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('source_epoch_id', sa.String(length=32), nullable=False),
    sa.Column('start_sample', sa.BigInteger(), nullable=False),
    sa.Column('end_sample', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.String(length=40), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', hattama.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_epoch_id'], ['source_epochs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audio_gaps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audio_gaps_source_epoch_id'), ['source_epoch_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_gaps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audio_gaps_source_epoch_id'))

    op.drop_table('audio_gaps')
    with op.batch_alter_table('source_epochs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_epochs_source_id'))

    op.drop_table('source_epochs')
    with op.batch_alter_table('transcript_segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transcript_segments_meeting_id'))
        batch_op.drop_index('ix_segments_rev_order')

    op.drop_table('transcript_segments')
    with op.batch_alter_table('speaker_bindings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_speaker_bindings_speaker_id'))

    op.drop_table('speaker_bindings')
    op.drop_table('pairing_codes')
    with op.batch_alter_table('ingest_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingest_tokens_capture_session_id'))

    op.drop_table('ingest_tokens')
    with op.batch_alter_table('evidence_spans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_spans_meeting_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_spans_action_id'))

    op.drop_table('evidence_spans')
    with op.batch_alter_table('capture_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_capture_sources_capture_session_id'))

    op.drop_table('capture_sources')
    with op.batch_alter_table('bot_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bot_sessions_meeting_id'))

    op.drop_table('bot_sessions')
    with op.batch_alter_table('action_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_revisions_action_id'))

    op.drop_table('action_revisions')
    with op.batch_alter_table('transcript_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transcript_revisions_meeting_id'))

    op.drop_table('transcript_revisions')
    with op.batch_alter_table('summary_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_summary_revisions_meeting_id'))

    op.drop_table('summary_revisions')
    with op.batch_alter_table('speakers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_speakers_meeting_id'))

    op.drop_table('speakers')
    with op.batch_alter_table('review_issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_issues_meeting_id'))

    op.drop_table('review_issues')
    with op.batch_alter_table('protocol_approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_protocol_approvals_meeting_id'))

    op.drop_table('protocol_approvals')
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participants_meeting_id'))

    op.drop_table('participants')
    with op.batch_alter_table('meeting_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meeting_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_meeting_members_meeting_id'))

    op.drop_table('meeting_members')
    with op.batch_alter_table('extraction_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extraction_runs_meeting_id'))

    op.drop_table('extraction_runs')
    with op.batch_alter_table('export_artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_export_artifacts_meeting_id'))

    op.drop_table('export_artifacts')
    with op.batch_alter_table('capture_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_capture_sessions_state'))
        batch_op.drop_index(batch_op.f('ix_capture_sessions_meeting_id'))

    op.drop_table('capture_sessions')
    with op.batch_alter_table('audio_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audio_assets_meeting_id'))

    op.drop_table('audio_assets')
    with op.batch_alter_table('action_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_items_meeting_id'))
        batch_op.drop_index(batch_op.f('ix_action_items_assignee_user_id'))
        batch_op.drop_index(batch_op.f('ix_action_items_assignee_participant_id'))

    op.drop_table('action_items')
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meetings_status'))
        batch_op.drop_index(batch_op.f('ix_meetings_owner_id'))

    op.drop_table('meetings')
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_sessions_user_id'))

    op.drop_table('auth_sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('resource_locks')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_status'))
        batch_op.drop_index(batch_op.f('ix_notifications_scheduled_for'))
        batch_op.drop_index(batch_op.f('ix_notifications_meeting_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_action_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('metric_samples', schema=None) as batch_op:
        batch_op.drop_index('ix_metrics_meeting_name')

    op.drop_table('metric_samples')
    with op.batch_alter_table('live_events', schema=None) as batch_op:
        batch_op.drop_index('ix_live_events_meeting')

    op.drop_table('live_events')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_meeting_id'))
        batch_op.drop_index('ix_jobs_claim')

    op.drop_table('jobs')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_object')
        batch_op.drop_index(batch_op.f('ix_audit_events_meeting_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_at'))

    op.drop_table('audit_events')
    # ### end Alembic commands ###
